web:
  image: yad88/phpapp
  ports:
    - "80:80"
  volumes:
    - /home/chiuser/kinometrica:/var/www
  links:
    - mysqldb

mysqldb:
  image: mysql/mysql-server:5.6
  ports:
    - "3306:3306"
  volumes:
    - /home/chiuser/kinometrica/db/kino.sql:/docker-entrypoint-initdb.d/kino.sql:ro
    - /home/chiuser/kinometrica/init.php:/docker-entrypoint-initdb.d/init.php:ro

  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    MYSQL_DATABASE: kino 

phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    restart: always
    ports:
       - '8080:80'
    links:
        - mysqldb
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
        PMA_HOST: mysqldb
